import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontTitulo = localFont({
  src: './fonts/PlayfairDisplay.ttf',
  weight: '400',
  variable: "--fontTitulo"
});

const fontTexto = localFont({
  src: './fonts/Inter.ttf',
  weight: '400',
  variable: "--fontTexto"
});




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontTitulo.variable} ${fontTexto.variable}`}>
        {children}
      </body>
    </html>
  );
}
