import type { Metadata } from "next";
import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import "./globals.css"
import { Montserrat } from "next/font/google"

export const metadata: Metadata = {
  title: "utilizando fontes",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  weight: ["400", "900"],
  subsets: ["latin"],

})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${montserrat.className}`}>
        <Theme>
        {children}
        </Theme>
      </body>
    </html>
  );
}
