import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontTitulo = localFont({
  src: './fonts/PlayfairDisplay.ttf',
  weight: '400',
  variable: "--fontTitulo"
});

const fontTexto = localFont({
  src: './fonts/Inter.ttf',
  weight: '400',
  variable: "--fontTexto"
});




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontTitulo.variable} ${fontTexto.variable}`} >
      <header>
          <div>
            <div className="site-logo">Universo em Foco</div>
            <p>Explore o incrível mundo da astronomia e descubra segredos do cosmos através de artigos, imagens e muito mais!</p>
          </div>
          <nav>
            <Link href={"/"} className="linkNavegacao">Início</Link>
            {" | "}
            <Link href={"/blog"} className="linkNavegacao">Blog</Link>
            {" | "}
            <Link href={"/loja"} className="linkNavegacao">Loja</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
